# basic slice viewer app generated by ChatGPT

library(shiny)
library(oro.nifti)

ui <- fluidPage(
  titlePanel("Neuroimaging Brain Slices Viewer"),
  sidebarLayout(
    sidebarPanel(
      fileInput("nifti_file", "Choose a NIFTI file"),
      sliderInput("slice", "Choose a slice to view", min = 1, max = 100, value = 50),
      radioButtons("orientation", "Choose orientation", choices = c("Axial", "Sagittal", "Coronal"), selected = "Axial")
    ),
    mainPanel(
      imageOutput("brain_slice")
    )
  )
)

server <- function(input, output) {
  nifti_data <- reactive({
    infile <- input$nifti_file
    if (is.null(infile))
      return(NULL)
    nifti_image <- readNIfTI(infile$datapath)
    return(nifti_image)
  })
  
  output$brain_slice <- renderImage({
    nifti_image <- nifti_data()
    if (is.null(nifti_image))
      return(NULL)
    if (input$orientation == "Axial") {
      img <- nifti_image[,,input$slice,1]
    } else if (input$orientation == "Sagittal") {
      img <- nifti_image[input$slice,,,-1]
    } else {
      img <- nifti_image[,input$slice,,1]
    }
    plot(img, col = grey(seq(0, 1, length = 256)))
  }, deleteFile = FALSE)
}

shinyApp(ui, server)
