name: Data Contribution
description: Contribute data to BrainEffeX
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing data to BrainEffeX! Please answer a few questions about your data contribution.
  
  - type: input
    id: name
    attributes:
      label: Name
      description: "Name"
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Info
      description: "Please provide an email address that we could use to contact you about the data."
    validations:
      required: true

  - type: checkboxes
    id: collection
    attributes:
      label: Data collection
      description: "Did you collect this data?"
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: input
    id: dataset-name
    attributes: 
      label: Dataset name
    validations:
      required: true

  - type: checkboxes
    id: map-type
    attributes: 
      label: Map type
      description: "Are you providing activation maps or functional connectivity?"
      options:
        - label: "Activation maps"
        - label: "Functional connectivity"
    validations:
      required: true

  - type: input
    id: preprocessing
    attributes: 
      label: Preprocessing
      description: "Which preprocessing steps did you perform? Please send us your preprocessing scripts if available."
    validations:
      required: true

  - type: input
    id: parcellation
    attributes: 
      label: Parcellation
      description: "Which parcellation did you use?"
    validations:
      required: true

  - type: input
    id: brainlife-link
    attributes: 
      label: Brainlife.io Link
      description: "If you haven't already, please upload your data to brainlife.io following the instructions in BrainEffeX/for_contributors/README.md. Please provide the link to the data from Brainlife.io here."
    validations:
      required: true

  - type: markdown
    attributes: 
      value: |
        **Thank you!** Your contribution is valuable to BrainEffeX.
