library(shinytest2)

test_that("{shinytest2} recording: BrainEffeX", {
  app <- AppDriver$new(variant = platform_variant(), name = "BrainEffeX", height = 746, 
      width = 1007)
  app$click("nextToPage2")
  app$click("nextToPage3")
  app$click("nextToPage4")
  app$click("closePage4")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "ABCD")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "HBN")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "HCP")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "HCP_EP")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "PNC")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "SLIM")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "UKB")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(map_type = "fc")
  app$set_inputs(dataset = "*")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(motion = "regression")
  app$set_inputs(map_type = "*")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(motion = "threshold")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(pooling = "net")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(estimate = "r_sq")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(tab = "Meta-Analysis")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(meta_analysis = "category")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(m_estimate = "r_sq")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(m_pooling = "net")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(m_motion = "regression")
  app$expect_values()
  app$expect_screenshot()
  app$click("showInstructions")
  app$expect_values()
  app$expect_screenshot()
})
